CREATE TABLE IF NOT EXISTS users_tb (
    id INT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(65) NOT NULL,
    username VARCHAR(65) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)